server:
  port: 9092
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

#management:
#  endpoint:
#    routes:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: *
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EA
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
